trigger:
- master

resources:
- repo: self

variables:
- name: appName
  value: tocgenerator

- name: tag
  value: $(Build.BuildId)

- name: imageNameWithoutTag
  value: $(dockerid)/$(appName)

- name: imageNameWithTag
  value: $(imageNameWithoutTag):$(tag)

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: docker build and push
      inputs:
        containerRegistry: 'my_docker_hub'
        repository: '$(imageNameWithoutTag)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '.'
        tags: $(tag)
        addPipelineData: false

    - task: Bash@3
      displayName: tag image as latest and push
      inputs:
        targetType: 'inline'
        script: |
          docker tag $(imageNameWithTag) $(imageNameWithoutTag):latest

    - task: Docker@2
      displayName: push latest tagged image
      inputs:
        containerRegistry: 'my_docker_hub'
        repository: $(imageNameWithoutTag)
        command: 'push'
        tags: 'latest'
        addPipelineData: false

    - task: SSH@0
      displayName: update k8s application image
      inputs:
        sshEndpoint: 'aliyun 47.102.201.58'
        runOptions: 'inline'
        inline: 'kubectl set image deploy/tocgenerator-deploy $(appName)=$(imageNameWithTag)'
        readyTimeout: '20000'